#!/bin/bash

if [ $# \< 1 ]; then echo Usage: mku filename; exit; fi

# default partiton = 3
PARTITION=3
if [ $# \> 1 ]; then PARTITION=$2; fi

VDISK=vdisk
SECTOR=$(sudo ./ptable vdisk $PARTITION)
OFFSET=$(sudo expr $SECTOR \* 512)

echo partition=$PARTITION sector=$SECTOR offset=$OFFSET
#read dummy

sudo mount -o loop,offset=$OFFSET $VDISK /mnt

echo compiling $1.c .....
as86 -o u.o u.s
bcc -c -ansi $1.c

echo linking .......
ld86 u.o $1.o mtxlib /usr/lib/bcc/libc.a #2> /dev/null

echo copying $1 into $VDISK/bin/$1
ls -la a.out

sudo cp -av a.out /mnt/bin/$1
sudo umount /mnt
rm a.out

echo done $1
